app:
  telegram-id: ${TELEGRAM_ID}
  version: 0.0.1-SNAPShOT
telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME}
    token: ${TELEGRAM_BOT_TOKEN}
  proxy:
    enable: ${PROXY_ENABLE:false}
    host: ${PROXY_HOST:}
    port: ${PROXY_PORT:}
    type: ${PROXY_TYPE:SOCKS5}
    user: ${PROXY_USERNAME:}
    password: ${PROXY_PASSWORD:}
openai:
  token: ${CHAT_GPT_TOKEN}